export enum CalendarActionKind {
  CHANGE_CURRENT_DATE = "CHANGE_CURRENT_DATE",
  CHANGE_CURRENT_YEAR = "CHANGE_CURRENT_YEAR",
  CHANGE_SELECTED_DATE = "CHANGE_SELECTED_DATE",
  CHANGE_VIEW = "CHANGE_VIEW",
}
